server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update # T?o b?ng t? ??ng n?u ch?a t?n t?i
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/  # Đảm bảo rằng Thymeleaf tìm thấy các file template trong thư mục /templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

